config/routes.rb
BatnaApp::Application.routes.draw do
  devise_for :users, controllers: {sessions: "devise/sessions"}
  root :to => "static_pages#index"

  get "/negotiations/retrievenegotiations" => "negotiations#retrieve_negotiations"
  get "/issues/retrieveissues" => "issues#retrieve_issues"

  post "/negotiations/newnegotiation" => "negotiations#new_negotiation"
  post "/issues/newissue" => "issues#new_issue"

  put "/negotiations/newnegotiation" => "negotiations#update_negotiation"
  put "/issues/newissue" => "issues#update_issue"

  match 'sign_in'  => 'sessions#new', :via => :get
  match 'sign_up' => 'users#new', :via => :get
  match 'new' => 'devise/sessions#new', :via => :get
  

  resource :session, :only => [:new, :create, :destroy]
  resource :account, :controller => 'users', :except => [:index, :destroy, :show, :edit]
  resource :static_pages
  resource :negotiations
  resource :issues

  

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :negotiation
  belongs_to :user

  attr_accessible :issue_name, :issue_outcome, :potential_points, :issue_points, :negotiation_id

end

app/models/negotiation.rb
class Negotiation < ActiveRecord::Base
	belongs_to :user
	has_many :issues

    attr_accessible :negotiation_name, :batna_name, :batna_points, :final_score, :completed, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :password
  attr_protected :encrypted_password

  has_many :negotiations
  has_many :issues

 
  validates :email, :presence => true, :uniqueness => true, :email => true
  validates :password, :presence => true, :confirmation => true
 


  def self.authenticate(email, pass)
    user = where(:email => email).first
    user && BCrypt::Password.new(user.encrypted_password) == pass ? user : nil
  end

  def password=(pass)
    return if pass.blank?
    @password = pass
    self.encrypted_password = BCrypt::Password.create(pass)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  private

  def require_user
    return if current_user

    respond_to do |format|
      format.html { redirect_to login_path }
      format.all  { render :text => 'unauthorized', :status => :unauthorized }
    end
  end

  # def current_user
    
  #   return @current_user if @current_user

  #   if session[:user_id]
  #     @current_user = User.find(session[:user_id])
  #   elsif (header = request.headers['Authorization'].to_s.sub('Basic ','')) != ''
  #     header = Base64.decode64(header).split(':')
  #     username = header.shift
  #     password = header.join(':')
  #     @current_user = User.authenticate(username, password)
  #   end
  # end

  def create_user_session(user)
    session[:user_id] = user.id
  end

  def destroy_user_session
    session[:user_id] = nil
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	respond_to :html, :json

	def new_issue
	  @issue = Issue.new(params[:issue])
	  @issue.user_id = session[:user_id]

	  if @issue.save
	    respond_to do |format|
	      format.json { render :json => @issue }
	    end
	  end
  end

  def update_issue
  	id_number = params[:issue]["id"]
    
    @issue = Issue.find_by(id: id_number)
    @issue.issue_name = params[:issue]["issue_name"]
    @issue.issue_outcome = params[:issue]["issue_outcome"]
    @issue.potential_points = params[:issue]["potential_points"]
    @issue.issue_points = params[:issue]["issue_points"]
   
    if @issue.save
      respond_to do |format|
        format.json { render :json => @issue }
      end
    end
  end

  def retrieve_issues
    @id = params[:negotiation_id]
    @issue = Issue.where(negotiation_id: @id).load

  	if @issue
  		respond_with do |format|
  			format.json { render :json => @issue }
  		end
  	end
  end

  def destroy
    Issue.destroy(params[:issue]["id"])
  end
end

app/controllers/negotiations_controller.rb
class NegotiationsController < ApplicationController
	respond_to :html, :json

	def new_negotiation
    
	  @negotiation = Negotiation.new(params[:negotiation])
    
	  @negotiation.user_id = current_user.id

	  if @negotiation.save
	    respond_to do |format|
	      format.json { render :json => @negotiation }
	    end
	  end
  end

  def update_negotiation
    id_number = params[:negotiation]["id"]
    
    @negotiation = Negotiation.find_by(id: id_number)
    @negotiation.negotiation_name = params[:negotiation]["negotiation_name"]
    @negotiation.batna_name = params[:negotiation]["batna_name"]
    @negotiation.batna_points = params[:negotiation]["batna_points"]
  
    if @negotiation.save
      respond_to do |format|
        format.json { render :json => @negotiation }
      end
    end
  end

  def retrieve_negotiations
    @id = current_user.id
    @negotiation = Negotiation.where(user_id: @id).last(5)

  	if @negotiation
  		respond_with do |format|
  			format.json { render :json => @negotiation }
  		end
  	end
  end

  def destroy
    Negotiation.destroy(params[:negotiation]["id"])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  respond_to :html, :json

  def create
  
    
    @user = User.authenticate(params[:user][:email], params[:user][:password])

    if @user
      create_user_session(@user)
     
      sign_in(@user)
      redirect_to '/'
     
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render :json => {:error => "Invalid email or password."} }
      end
    end
  end

  def destroy
    destroy_user_session
    redirect_to '/login', :notice => "Logged out."
  end





end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  # before_filter :require_user

  def index
  	@current_user = current_user
  	@logged_in = true
  end

  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show, :new, :create]
  

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
       respond_to do |format|
              format.json { render :json => @user }
      end
      flash[:notice] = 'Account created.'
      create_user_session(@user)
      redirect_to :static_pages

    else
     redirect_to :back
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/negotiations_helper.rb
module NegotiationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BatnaApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

	<div class="authenticate">
				<% if @logged_in %>
				<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
				<% else %>
				<a href= "sign_in">Sign In</a>
				<a href="sign_up">Sign Up</a>
				<% end %>
			</div>

<%= yield %>
	
	</div>

</body>
</html>

app/views/static_pages/index.html.erb
<div class="negotiationListView">
</div>

<div class="negotiationFormView">
<div class="newNegotiationButton"></div>
</div>

<div class="issuesContainer">

	<div class="issueView">
	</div>
	<div class="issueEvalView"></div>
	<div class="issueFormView"></div>

</div>

app/views/users/new.html.erb
<!-- <div id='signup-view'>
  <div class="page-header">
    <h1>My BATNA</h1>
  </div>

  <%= form_tag account_path, :class => 'form-horizontal' do %>
    <div class="control-group">
      <%= label_tag :username, nil, :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag :username, nil %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :email, nil, :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag :email, nil %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :password, nil, :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :password_confirmation, 'Confirm', :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password_confirmation %>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag "Signup", :class => 'btn ' %>
      <div class='clear'></div>
    </div>

  <% end %>
  <div class='clear'></div>
</div> -->